home/urls.py
# from django.contrib import admin
from django.urls import path, re_path

from wzuJudge import settings
from . import views
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',views.index),
    path('about',views.about),
    path('test',views.temp),
    # re_path('(\w+)',views.problem_detail),

]

user/urls.py
# from django.contrib import admin
from django.urls import path, re_path

from wzuJudge import settings
from . import views
urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('',views.index),
    path('sign_in',views.sign_in),
    path('get_valid_img',views.get_valid_img),
    path('sign_up',views.sign_up),
    path('logout',views.logout),
    path('profile', views.profile),
    path('profile/account_settings',views.account_settings),
    path('profile/change_password',views.change_password),
    path('profile/change_email',views.change_email),
    path('settings',views.create_announcement),
    path('add_problem',views.add_problem),
    path('create_contest',views.create_contest),
    path('create_announcement',views.create_announcement),
    path('upload',views.upload),
    path('get_problem_by_id',views.get_problem_by_id),


]

wzuJudge/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from home import views
from wzuJudge import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),
    path('index',views.index),
    path('404',views.page_not_found),
    path('home/',include('home.urls')),
    path('user/', include('user.urls')),
    path('problem',include('problem.urls')),
    path('status',include('status.urls')),
    path('rank',include('rank.urls')),
    path('contest',include('contest.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

# handler400 = views.bad_request
# handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.error

user/forms.py
from django import forms
from django.forms import widgets
from user.models import UserInfo
from django.core.exceptions import ValidationError


# form 组件
class RegisterForm(forms.Form):
    username = forms.CharField(max_length=8, label="用户名",
                               widget=widgets.TextInput(attrs={"class": "form-control", "placeholder": "Username"}))
    password = forms.CharField(min_length=4, label="密码",
                               widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}))
    repeat_password = forms.CharField(min_length=4, label="确认密码",
                                      widget=widgets.PasswordInput(
                                          attrs={"class": "form-control", "placeholder": "Confirm"}))
    email = forms.EmailField(label="邮箱",
                             widget=widgets.EmailInput(attrs={"class": "form-control", "placeholder": "Email"}))

    # 局部钩子
    def clean_username(self):
        username = self.cleaned_data.get('username')
        user = UserInfo.objects.filter(username=username)
        if user:
            raise ValidationError("用户已存在")
        else:
            return username

    # 全局钩子
    def clean(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("repeat_password"):
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")

user/views.py
import datetime
import os

from django.contrib import auth
from django.db import transaction
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.utils import timezone
from django.utils.timezone import utc
import pytz
from django.views.decorators.csrf import csrf_exempt

from user.check_permission import superuser_only
from user.forms import RegisterForm
from user.models import UserInfo, Problem, Simple_Put, Contest, Problem_To_Contest, Announcement


def sign_in(request):
    if request.is_ajax():
        username = request.POST.get("username")
        password = request.POST.get("password")
        valid_code = request.POST.get("valid_code")
        next = request.GET.get("next",'/index')
        res = {"state": False, "msg": None,"url": next}
        s_valid_code = request.session.get("valid_code")
        # 判断验证码是否正确
        if valid_code.upper() == s_valid_code.upper():
            user = auth.authenticate(username=username, password=password)
            if user:  # 若此用户存在则进行登录操作
                res['state'] = True
                auth.login(request, user)
            else:
                res['msg'] = '用户名或者密码错误'
        else:
            res['msg'] = '验证码错误'

        return JsonResponse(res)

    return render(request, 'signin.html')


def get_valid_img(request):
    from PIL import Image
    from PIL import ImageDraw, ImageFont
    from random import randint
    import random
    width = 160
    height = 40

    def get_random_color():
        return (randint(0, 255), randint(0, 255), randint(0, 255))

    def get_background_color():
        return (randint(200, 255), randint(200, 255), randint(200, 255))

    def get_font_color():
        return (randint(0, 100), randint(0, 100), randint(0, 100))

    image = Image.new('RGB', (width, height), get_background_color())

    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype("static/assets/fonts/kumo.ttf", 32)
    temp = []
    for i in range(5):
        random_num = str(randint(0, 9))
        random_low_alpha = chr(randint(97, 122))
        random_upper_alpha = chr(randint(65, 90))
        random_char = random.choice([random_num, random_low_alpha, random_upper_alpha])
        draw.text((24 + i * 24, randint(0, 15)), random_char, get_font_color(), font=font)

        # 保存随机字符
        temp.append(random_char)

    # 噪点

    for i in range(20):
        draw.point([random.randint(0, width), random.randint(0, height)], fill=get_random_color())
        x = random.randint(0, width)
        y = random.randint(0, height)
        # 弧线
        draw.arc((x, y, x + 4, y + 4), 0, 90, fill=get_random_color())

    # 在内存中生成图片
    from io import BytesIO
    f = BytesIO()
    image.save(f, 'png')
    data = f.getvalue()
    f.close()

    valid_code = "".join(temp)
    request.session["valid_code"] = valid_code

    return HttpResponse(data)


def sign_up(request):
    form = RegisterForm()
    context = {
        'form': form,
    }

    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        res = {'username': None, 'error_dict': None}
        if register_form.is_valid():
            # print(register_form.cleaned_data)

            username = request.POST.get('username')
            password = request.POST.get('password')
            email = request.POST.get('email')
            user = UserInfo.objects.create_user(username=username, password=password, email=email)
            res['username'] = user.username
        else:
            # print(register_form.errors)
            res['error_dict'] = register_form.errors
        return JsonResponse(res)
    return render(request, 'signup.html', context=context)


@login_required(login_url='/user/sign_in')
def logout(request):
    auth.logout(request)
    return redirect('/index')

@login_required(login_url='/user/sign_in')
def profile(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            res = {'msg': None}
            last_name = request.POST.get('last_name')
            school = request.POST.get('school')
            student_id = request.POST.get('student_id')
            mood = request.POST.get('mood')
            telephone = request.POST.get('telephone')
            avatar = request.FILES.get('avatar')
            username = request.user.username

            if avatar:
                avatar_name = 'avatars/' + username + '.' + avatar.name.split('.')[-1]
                result = UserInfo.objects.filter(username=username).update(last_name=last_name, school=school,
                                                                           telephone=telephone,
                                                                           student_id=student_id, mood=mood,
                                                                           avatar=avatar_name)
                with open('media/' + avatar_name, 'wb') as f:
                    for line in avatar:
                        f.write(line)
            else:
                result = UserInfo.objects.filter(username=request.user.username).update(last_name=last_name,
                                                                                        school=school,
                                                                                        telephone=telephone,
                                                                                        student_id=student_id,
                                                                                        mood=mood)
            return JsonResponse(res)
        return render(request, 'profile_info.html')
    # return redirect('/index')
    return render(request, '404.html')

@login_required(login_url='/user/sign_in')
def account_settings(request):
    if request.user.is_authenticated:
        return render(request, 'profile_account.html')
    return render(request, '404.html')

@login_required(login_url='/user/sign_in')
def change_password(request):
    if request.method == "POST":
        res = {'status': False, 'msg': None}
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')
        confirm_new_password = request.POST.get('confirm_new_password')
        user = UserInfo.objects.filter(username=request.user.username).first()
        # user = request.user
        print()
        if new_password == confirm_new_password:
            if user.check_password(old_password):
                user.set_password(new_password)
                user.save()
                res['status'] = True
            else:
                res['msg'] = "密码错误"
        else:
            res['msg'] = "两次密码不一致"

        return JsonResponse(res)

@login_required(login_url='/user/sign_in')
def change_email(request):
    if request.method == "POST":
        res = {'status': False, 'msg': None}
        current_password = request.POST.get('current_password')
        new_email = request.POST.get('new_email')
        # user = UserInfo.objects.filter(username=request.user.username).first()
        user = request.user
        if user.check_password(current_password):
            UserInfo.objects.filter(username=user.username).update(email=new_email)
            res['status'] = True
        else:
            res['msg'] = "密码错误"

        return JsonResponse(res)



# 以下为管理员操作

@superuser_only
def admin_settings(request):
    user = request.user
    # user.is_superuser
    return render(request, 'admin_manage.html')

@superuser_only
def get_problem_by_id(request):
    if request.is_ajax():
        id = request.POST.get('problem_id')
        res = {'status': False, 'msg': None, 'data':None}
        try:
            problem = Problem.objects.get(id=id)
        except Exception:
            res['msg'] = '无法获取此Id对应的问题'
            return JsonResponse(res)
        res['status'] = True
        res['data'] = {'id':problem.id,'title':problem.title,'level':problem.level,'rule':problem.rule}
        return JsonResponse(res)

@superuser_only
def create_contest(request):
    if request.is_ajax():
        res = {'status': False, 'msg': None}
        c_contest_name = request.POST.get('c_contest_name')
        c_protected = request.POST.get('c_protected',0)
        c_password = request.POST.get('c_password','')
        c_start_time = request.POST.get('c_start_time').replace("T", " ")
        c_end_time = request.POST.get('c_end_time').replace("T", " ")
        start_time = timezone.datetime.strptime(c_start_time, '%Y-%m-%d %H:%M')
        start_time = start_time - datetime.timedelta(hours=8)
        start_time = start_time.replace(tzinfo=utc)
        end_time = timezone.datetime.strptime(c_end_time, '%Y-%m-%d %H:%M')
        end_time = end_time - datetime.timedelta(hours=8)
        end_time = end_time.replace(tzinfo=utc)
        c_description = request.POST.get('c_description','')
        c_orders = request.POST.getlist('c_orders[]')
        c_ids = request.POST.getlist('c_ids[]')

        try:
            with transaction.atomic():
                contest = Contest.objects.create(title=c_contest_name,type=int(c_protected), password=c_password, start_time=start_time,
                                                end_time=end_time, description=c_description,creator_id=request.user.id)
                for i in range(len(c_ids)):
                    problem = Problem.objects.get(id=int(c_ids[i].strip()))
                    Problem_To_Contest.objects.create(problem=problem,contest=contest,p_id=c_orders[i])
        except Exception as e:
            print(repr(e))
            res['msg'] = "创建比赛失败"
            return JsonResponse(res)
        res['status'] = True
        res['msg'] = "创建比赛成功"
        return JsonResponse(res)
    context = {
        'flag':3,  # 3 创建比赛active
    }
    return render(request,'create_contest.html',context=context)


@superuser_only

user/templates/create_announcement.html
{% extends 'base_admin.html' %}

{% block title %}

{% endblock %}

{% block mycss %}

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Create Announcement</h1>
        </div>
    </div>
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row md-5">
                        <div class="col-lg-12 form-group">
                            <h2>1. Title:</h2>
                            <p class="lead">
                                添加公告标题
                            <p>

                            </p>
                            <input class="form-control" id="title">
                            <h2>2. Description</h2>
                            <p class="lead">
                                添加公告描述
                            </p>
                            <textarea cols="10" id="announcement" name="announcement" rows="10"></textarea>
                            <button style="margin-top: 30px" type="button" id="submit_a"
                                            class="btn btn-primary btn-gradient waves-effect waves-light"><span
                                            class="gradient">
												提交
											</span></button>
                        </div>

                    </div>
                </div>
            </div>

            </div>
        </div>
{% endblock %}

{% block myjs %}
    <script type="text/javascript" src="/static/assets/plugins/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="/static/assets/plugins/ckeditor/adapters/jquery.js"></script>
    {% csrf_token %}
    <script>

        var config = {
            toolbarGroups: [
                {name: 'clipboard', groups: ['clipboard', 'undo']},
                {name: 'editing', groups: ['find', 'selection', 'spellchecker', 'editing']},
                {name: 'links', groups: ['links']},
                {name: 'insert', groups: ['insert']},
                {name: 'forms', groups: ['forms']},
                {name: 'tools', groups: ['tools']},
                {name: 'document', groups: ['mode', 'document', 'doctools']},
                {name: 'others', groups: ['others']},
                '/',
                {name: 'basicstyles', groups: ['basicstyles', 'cleanup']},
                {name: 'paragraph', groups: ['list', 'indent', 'blocks', 'align', 'bidi', 'paragraph']},
                {name: 'styles', groups: ['styles']},
                {name: 'colors', groups: ['colors']},
                {name: 'about', groups: ['about']}
            ],
            removeButtons: 'About,Source',
            extraPlugins: 'codesnippet',
            codeSnippet_theme: 'github',
            height: 300,
            // Configure your file manager integration. This example uses CKFinder 3 for PHP.
            filebrowserBrowseUrl: '/apps/ckfinder/3.4.5/ckfinder.html',
            filebrowserImageBrowseUrl: '/apps/ckfinder/3.4.5/ckfinder.html?type=Images',
            filebrowserUploadUrl: '/apps/ckfinder/3.4.5/core/connector/php/connector.php?command=QuickUpload&type=Files',
            filebrowserImageUploadUrl: '/user/upload',

        };
        announcement = CKEDITOR.replace('announcement', config);


        $("#submit_a").click(function () {
            $.ajax({
                {% autoescape off%}url:{{ myurl|default:"''" }},{% endautoescape %}
                type: 'post',
                data: {
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                    title: $("#title").val(),
                    description: announcement.getData(),
                },
                success: function (res) {
                    if(res.status){
                        alert(res.msg);
                        location.href = res.url;
                    }else{
                        alert(res.msg);
                    }

                }
            })
        })



    </script>

{% endblock %}

user/templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/assets/img/favicon.png">

    <title>Sign In</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700&amp;subset=latin-ext"
          rel="stylesheet">

    <!-- CSS - REQUIRED - START -->
    <!-- Batch Icons -->
    <link rel="stylesheet" href="/static/assets/fonts/batch-icons/css/batch-icons.css">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="/static/assets/css/bootstrap/bootstrap.min.css">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="/static/assets/css/bootstrap/mdb.min.css">
    <!-- Custom Scrollbar -->
    <link rel="stylesheet" href="/static/assets/plugins/custom-scrollbar/jquery.mCustomScrollbar.min.css">
    <!-- Hamburger Menu -->
    <link rel="stylesheet" href="/static/assets/css/hamburgers/hamburgers.css">

    <!-- CSS - REQUIRED - END -->

    <!-- CSS - OPTIONAL - START -->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/assets/fonts/font-awesome/css/font-awesome.min.css">

    <!-- CSS - DEMO - START -->
    <link rel="stylesheet" href="/static/assets/demo/css/ui-icons-batch-icons.css">
    <!-- CSS - DEMO - END -->

    <!-- CSS - OPTIONAL - END -->

    <!-- QuillPro Styles -->
    <link rel="stylesheet" href="/static/assets/css/quillpro/quillpro.css">
</head>

<body>

<div class="container-fluid">
    <div class="row">
        <div class="right-column sisu">
            <div class="row mx-0">
                <div class="col-md-7 order-md-2 signin-right-column px-5 bg-dark">
                    <a class="signin-logo d-sm-block d-md-none" href="#">
                        <img src="/static/assets/img/logo-white.png" width="145" height="32.3" alt="QuillPro">
                    </a>
                    <h1 class="display-4">Sign In To get Started</h1>
                    <p class="lead mb-5">
                        Big data latte SpaceTeam unicorn cortado hacker physical computing paradigm.
                    </p>
                </div>
                <div class="col-md-5 order-md-1 signin-left-column bg-white px-5">
                    <a class="signin-logo d-sm-none d-md-block" href="#">
                        <img src="/static/assets/img/logo-dark.png" width="145" height="32.3" alt="QuillPro">
                    </a>
                    <form>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">用户名</label>
                            <input type="text" class="form-control" id="username" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <label for="password">密码</label>
                            <input type="password" class="form-control" id="password" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <label for="valid_code">验证码</label>
                            <div class="row">
                                <div class="col-md-8">
                                    <input type="text" class="form-control" id="valid_code" placeholder="Valid Code">
                                </div>
                                <div class="col-md-4">
                                    <img width="100%" class="rounded" id="valid_img" height="40" src="/user/get_valid_img" alt="验证码">
                                </div>
                            </div>
                        </div>
                        <button type="button" id="sign_in_btn" class="btn btn-primary btn-gradient btn-block">
                            <i class="batch-icon batch-icon-key"></i>
                            Sign In
                        </button>
                        <hr>
                        <p class="text-center">
                            还没有账号吗? <a href="/user/sign_up">快来注册吧</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- SCRIPTS - REQUIRED START -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- Bootstrap core JavaScript -->
<!-- JQuery -->
<script type="text/javascript" src="/static/assets/js/jquery/jquery-3.1.1.min.js"></script>
<!-- Popper.js - Bootstrap tooltips -->
<script type="text/javascript" src="/static/assets/js/bootstrap/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="/static/assets/js/bootstrap/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="/static/assets/js/bootstrap/mdb.min.js"></script>
<!-- Velocity -->
<script type="text/javascript" src="/static/assets/plugins/velocity/velocity.min.js"></script>
<script type="text/javascript" src="/static/assets/plugins/velocity/velocity.ui.min.js"></script>
<!-- Custom Scrollbar -->
<script type="text/javascript"
        src="/static/assets/plugins/custom-scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
<!-- jQuery Visible -->
<script type="text/javascript" src="/static/assets/plugins/jquery_visible/jquery.visible.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script type="text/javascript" src="/static/assets/js/misc/ie10-viewport-bug-workaround.js"></script>

<!-- SCRIPTS - REQUIRED END -->

<!-- SCRIPTS - OPTIONAL START -->
<!-- Image Placeholder -->
<script type="text/javascript" src="/static/assets/js/misc/holder.min.js"></script>
<!-- SCRIPTS - OPTIONAL END -->

<!-- QuillPro Scripts -->
<script type="text/javascript" src="/static/assets/js/scripts.js"></script>

<script type="text/javascript">
    $("#sign_in_btn").on("click", function () {
        $.ajax({
            url: "",
            type: "post",
            data: {
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                username: $("#username").val(),
                password: $("#password").val(),
                valid_code: $("#valid_code").val(),
            },
            success: function (data) {
                console.log(data);
                if (data.state) {
                    location.href = data.url
                } else {
                    alert(data.msg);
                    $(".errors").text(data.msg)
                }
            }
        })
    });

    $("#valid_img").click(function () {
        $(this)[0].src += "?"
    });
</script>
</body>
</html>

user/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="/static/assets/img/favicon.png">

	<title>Sign Up</title>

	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700&amp;subset=latin-ext" rel="stylesheet">

	<!-- CSS - REQUIRED - START -->
	<!-- Batch Icons -->
	<link rel="stylesheet" href="/static/assets/fonts/batch-icons/css/batch-icons.css">
	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="/static/assets/css/bootstrap/bootstrap.min.css">
	<!-- Material Design Bootstrap -->
	<link rel="stylesheet" href="/static/assets/css/bootstrap/mdb.min.css">
	<!-- Custom Scrollbar -->
	<link rel="stylesheet" href="/static/assets/plugins/custom-scrollbar/jquery.mCustomScrollbar.min.css">
	<!-- Hamburger Menu -->
	<link rel="stylesheet" href="/static/assets/css/hamburgers/hamburgers.css">

	<!-- CSS - REQUIRED - END -->

	<!-- CSS - OPTIONAL - START -->
	<!-- Font Awesome -->
	<link rel="stylesheet" href="/static/assets/fonts/font-awesome/css/font-awesome.min.css">

	<!-- CSS - DEMO - START -->
	<link rel="stylesheet" href="/static/assets/demo/css/ui-icons-batch-icons.css">
	<!-- CSS - DEMO - END -->

	<!-- CSS - OPTIONAL - END -->

	<!-- QuillPro Styles -->
	<link rel="stylesheet" href="/static/assets/css/quillpro/quillpro.css">
</head>

<body>

	<div class="container-fluid">
		<div class="row">
			<div class="right-column sisu">
				<div class="row mx-0">
					<div class="col-md-7 order-md-2 signin-right-column px-5 bg-dark">
						<a class="signin-logo d-sm-block d-md-none" href="#">
							<img src="/static/assets/img/logo-white.png" width="145" height="32.3" alt="QuillPro">
						</a>
						<h1 class="display-4">Sign Up For An Account Today</h1>
						<p class="lead mb-5">
							Big data latte SpaceTeam unicorn cortado hacker physical computing paradigm.
						</p>
					</div>
					<div class="col-md-5 order-md-1 signin-left-column bg-white px-5">
						<a class="signin-logo d-sm-none d-md-block" href="#">
							<img src="/static/assets/img/logo-dark.png" width="145" height="32.3" alt="QuillPro">
						</a>
						<form>
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
								    <label  for="">{{ field.label }}</label><span class="errors pull-right"></span>
                                    {{ field }}
							    </div>
                            {% endfor %}
							<button type="button" id="sign_up_btn" class="btn btn-primary btn-gradient btn-block">
								<i class="batch-icon batch-icon-quill"></i>
								Sign Up
							</button>
							<hr>
							<p class="text-center">
								已经有账号了? <a href="/user/sign_in">点此登录</a>
							</p>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- SCRIPTS - REQUIRED START -->
	<!-- Placed at the end of the document so the pages load faster -->
	<!-- Bootstrap core JavaScript -->
	<!-- JQuery -->
	<script type="text/javascript" src="/static/assets/js/jquery/jquery-3.1.1.min.js"></script>
	<!-- Popper.js - Bootstrap tooltips -->
	<script type="text/javascript" src="/static/assets/js/bootstrap/popper.min.js"></script>
	<!-- Bootstrap core JavaScript -->
	<script type="text/javascript" src="/static/assets/js/bootstrap/bootstrap.min.js"></script>
	<!-- MDB core JavaScript -->
	<script type="text/javascript" src="/static/assets/js/bootstrap/mdb.min.js"></script>
	<!-- Velocity -->
	<script type="text/javascript" src="/static/assets/plugins/velocity/velocity.min.js"></script>
	<script type="text/javascript" src="/static/assets/plugins/velocity/velocity.ui.min.js"></script>
	<!-- Custom Scrollbar -->
	<script type="text/javascript" src="/static/assets/plugins/custom-scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
	<!-- jQuery Visible -->
	<script type="text/javascript" src="/static/assets/plugins/jquery_visible/jquery.visible.min.js"></script>
	<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
	<script type="text/javascript" src="/static/assets/js/misc/ie10-viewport-bug-workaround.js"></script>

	<!-- SCRIPTS - REQUIRED END -->

	<!-- SCRIPTS - OPTIONAL START -->
	<!-- Image Placeholder -->
	<script type="text/javascript" src="/static/assets/js/misc/holder.min.js"></script>
	<!-- SCRIPTS - OPTIONAL END -->

	<!-- QuillPro Scripts -->
	<script type="text/javascript" src="/static/assets/js/scripts.js"></script>
    <script type="text/javascript">
        $("#sign_up_btn").click(function () {
        $.ajax({
            url: "",
            type: "post",
            data: {
                username:$("#id_username").val(),
                password:$("#id_password").val(),
                repeat_password:$("#id_repeat_password").val(),
                email:$("#id_email").val(),
                csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
            },
            success: function (data) {
                if (data.username) { // 注册成功

                    location.href = "/user/sign_in";
                } else {// 注册失败
                    console.log(data.error_dict);
                    // q清空错误信息
                    $("form .errors").html("");
                    $("form .form-group").removeClass("has-danger");
                    $("form input").removeClass("border-danger");

                    // 加载错误信息
                    $.each(data.error_dict, function (field, error_list) {
                        if (field == "__all__") {  // 全局钩子使用的时候错误信息的键为__all__
                            $("#id_repeat_password").prev().html(error_list[0]).css("color", 'red');
                            $("#id_repeat_password").parent().addClass("has-danger")
                            $("#id_repeat_password").addClass("border-danger")
                            // 使用bootstrap将框变红
                        }
                        $("#id_" + field).prev().html(error_list[0]).css("color", 'red');
                        $("#id_" + field).parent().addClass("has-danger");
                        $("#id_" + field).addClass("border-danger")
                    });
                }

            },
        });

    });
    </script>
</body>
</html>