contest/urls.py
# from django.contrib import admin
from django.urls import path, re_path

from wzuJudge import settings
from . import views
app_name = 'contest'
urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('',views.index),
    # path('about',views.about),
    # re_path('(\w+)',views.problem_detail),
    path('',views.contest_list),
    path('/<int:contest_id>',views.contest_detail),
    path('/<int:contest_id>/overview',views.contest_detail),
    path('/<int:contest_id>/announcements',views.announcements),
    path('/<int:contest_id>/problems',views.problem_list),
    path('/<int:contest_id>/submissions',views.status_list),
    path('/<int:contest_id>/rank',views.rank),
    path('/<int:contest_id>/create_announcement',views.create_announcement, name='create_announcement'),
    path('/<int:contest_id>/edit_contest',views.edit_contest),
    path('/<int:contest_id>/problem/<str:p_id>',views.problem_detail),

]

home/urls.py
# from django.contrib import admin
from django.urls import path, re_path

from wzuJudge import settings
from . import views
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',views.index),
    path('about',views.about),
    path('test',views.temp),
    # re_path('(\w+)',views.problem_detail),

]

wzuJudge/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from home import views
from wzuJudge import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),
    path('index',views.index),
    path('404',views.page_not_found),
    path('home/',include('home.urls')),
    path('user/', include('user.urls')),
    path('problem',include('problem.urls')),
    path('status',include('status.urls')),
    path('rank',include('rank.urls')),
    path('contest',include('contest.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

# handler400 = views.bad_request
# handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.error

contest/models.py
from django.db import models

# Create your models here.

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.


class UserInfo(AbstractUser):
    id = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11, null=True, unique=True, blank=True)
    avatar = models.FileField(upload_to='avatars/', default="avatars/default.png")
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    student_id = models.CharField(max_length=20, null=True, unique=True, blank=True)
    school = models.CharField(max_length=64, null=True, blank=True)
    mood = models.CharField(max_length=255, null=True, blank=True)
    ac_number = models.IntegerField(default=0, verbose_name="正确提交数量")
    total_number = models.IntegerField(default=0, verbose_name="全部提交数量")
    problems = models.ManyToManyField(
        to='Problem',
        through='UserInfo_To_Problem',
        through_fields=('user', 'problem'),
    )

    def __str__(self):
        return self.username


class Contest(models.Model):
    """比赛表"""
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, verbose_name='比赛标题')
    description = models.TextField(verbose_name='比赛描述', null=True, blank=True)
    # announcement = models.ForeignKey(to="Announcement", to_field='id', null=True, blank=True,
    #                                  on_delete=models.DO_NOTHING, verbose_name='公告')
    status = models.IntegerField(verbose_name='比赛状态', default=0)  # 0 未开始 1 进行中 2 结束
    start_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    type = models.IntegerField(verbose_name='比赛类型', default=0)  # 0 为公开 1 为私有
    password = models.CharField(max_length=32, verbose_name='参加比赛密码', null=True, blank=True)
    creator_id = models.IntegerField(verbose_name='创建者ID')
    users = models.ManyToManyField(
        to='UserInfo',
        through='Contest_To_UserInfo',
        through_fields=('contest', 'user'),
    )

    def __str__(self):
        return str(self.id) + self.title


class Contest_To_UserInfo(models.Model):
    """比赛与用户的多对多表"""
    id = models.AutoField(primary_key=True)
    contest = models.ForeignKey(to='Contest', to_field='id', on_delete=models.CASCADE)
    user = models.ForeignKey(to='UserInfo', to_field='id', on_delete=models.CASCADE)
    ac_number = models.IntegerField(verbose_name='正确提交数量', default=0)
    total_number = models.IntegerField(verbose_name='正确提交数量',default=0)
    total_time = models.CharField(verbose_name='答题总时间',max_length=64,null=True,blank=True,default='0')

    class Meta:
        unique_together = [
            ('contest', 'user')
        ]

    def __str__(self):
        return str(self.id) + "+" + str(self.contest.title) + "+" + str(self.user.id)


class Contest_User_Problem(models.Model):
    """针对单个比赛单个用户对于比赛中所有题解答的记录"""
    id = models.AutoField(primary_key=True)
    problem = models.ForeignKey(to='Problem', to_field='id', on_delete=models.DO_NOTHING)
    contest_To_User = models.ForeignKey(to='Contest_To_UserInfo', to_field='id', on_delete=models.DO_NOTHING)
    ac_number = models.IntegerField(verbose_name='正确提交数',default=0)
    ac_time = models.CharField(verbose_name='真确提交时间', max_length=64,null=True,blank=True)
    wrong_number = models.IntegerField(verbose_name='错误提交数', default=0)

    class Meta:
        unique_together = [
            ('problem', 'contest_To_User')
        ]

    def __str__(self):
        return str(self.id)


class Problem(models.Model):
    """ 问题表，存储问题相关字段"""
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, null=False, unique=False, verbose_name='题目标题')
    time_limit = models.IntegerField(default=0, verbose_name='时间限制')
    mem_limit = models.IntegerField(default=0, verbose_name='内存限制')
    ac_number = models.IntegerField(default=0, verbose_name='ac数')
    submit_number = models.IntegerField(default=0, verbose_name='提交数量')
    rule = models.CharField(max_length=255, verbose_name='判题规则', default='0') # 0 为严格比较 1 为 特殊比较
    spj_code = models.TextField(verbose_name='特判代码', null=True, blank=True)
    content = models.TextField(verbose_name='题目描述')
    input = models.TextField(verbose_name='输入描述')
    output = models.TextField(verbose_name='输出描述')
    # simple = models.ForeignKey(to='Simple_Put', to_field='id', on_delete=models.DO_NOTHING)
    hint = models.TextField(verbose_name='提示', null=True,blank=True)
    level = models.CharField(max_length=32, verbose_name='题目难度',default='Low')  #
    hide = models.IntegerField(default=0, verbose_name='时候隐藏')  # 0 不隐藏，1 隐藏
    # 为比赛添加
    contests = models.ManyToManyField(
        to='Contest',
        through='Problem_To_Contest',
        through_fields=('problem', 'contest')
    )
    # simple = models.ManyToManyField(to='Simple_Put')

    def __str__(self):
        return str(self.id) + self.title


class Simple_Put(models.Model):
    id = models.AutoField(primary_key=True)
    problem = models.ForeignKey(to='problem',to_field='id',on_delete=models.CASCADE)
    simple_input = models.TextField(verbose_name='输出样例',null=True,blank=True)
    simple_output = models.TextField(verbose_name='输出样例',null=True,blank=True)


class Problem_To_Contest(models.Model):
    """ 问题与比赛的多对多表"""
    id = models.AutoField(primary_key=True)
    problem = models.ForeignKey(to='Problem', to_field='id', on_delete=models.DO_NOTHING)
    contest = models.ForeignKey(to='Contest', to_field='id', on_delete=models.DO_NOTHING)
    ac_num = models.IntegerField(verbose_name='比赛正确提交次数', default=0)
    total_num = models.IntegerField(verbose_name='比赛全部提交次数', default=0)
    p_id = models.CharField(max_length=255, verbose_name='比赛中的标题',null=True,blank=True)

    class Meta:
        unique_together = [
            ('contest', 'problem')
        ]


class UserInfo_To_Problem(models.Model):  # 用户与问题多对多关系表
    """用户与问题多对多关系表，用来在非比赛的题目中此用户是否AC"""
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(to='UserInfo', to_field='id', on_delete=models.CASCADE)
    problem = models.ForeignKey(to='Problem', to_field='id', on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('user', 'problem')
        ]

    def __str__(self):
        return self.user.username + self.problem.title


class Submit(models.Model):
    """题目提交表"""
    solution_id = models.AutoField(primary_key=True, verbose_name='提交编号')
    problem = models.ForeignKey(to='Problem', to_field='id', on_delete=models.DO_NOTHING)
    user = models.ForeignKey(to='UserInfo', to_field='id', on_delete=models.DO_NOTHING)
    language = models.CharField(max_length=64, verbose_name='编程语言')
    # contest_id = models.CharField(verbose_name='比赛编号', max_length=64, null=True)
    contest = models.ForeignKey(verbose_name='比赛编号',to='Contest',to_field='id', null=True,blank=True,on_delete=models.DO_NOTHING)
    submit_time = models.DateTimeField(verbose_name='提交时间',auto_now_add=True)

    def __str__(self):
        return str(self.solution_id)


class Code(models.Model):
    """代码表已submit表一对一用来存储代码与判题相关的参数"""
    id = models.AutoField(primary_key=True)
    submit = models.OneToOneField(to='Submit', to_field='solution_id', on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True, verbose_name='提交时间')
    content = models.TextField(verbose_name='代码')
    spend_time = models.IntegerField(verbose_name='消耗时间', null=True, blank=True)
    spend_mem = models.IntegerField(verbose_name='消耗内存', null=True, blank=True)
    result = models.IntegerField(verbose_name='结果', default=0)
    message = models.TextField(verbose_name='错误信息', null=True, blank=True)

    def __str__(self):
        return self.result


class Announcement(models.Model):
    """公告表"""
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, verbose_name='公告标题')
    description = models.TextField(verbose_name='公告描述')
    belong_contest = models.IntegerField(default=0, verbose_name='是否属于比赛')  # 0 全局，1 属于比赛
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    create_author = models.ForeignKey(to='UserInfo', to_field='id', verbose_name='发布者', on_delete=models.DO_NOTHING)
    contest = models.ForeignKey(to='Contest',to_field='id',null=True,blank=True,on_delete=models.CASCADE)
    def __str__(self):
        return self.title

contest/templates/contest_announcement.html
{% extends 'base_contest.html' %}

{% block title %}

{{ contest.title }} | 公告
{% endblock %}

{% block mycss %}

{% endblock %}

{% block leftcard %}

    <div class="col-md-10">
        <div class="row">
            <div class="col-md-10">
            <h1>Announcements</h1>
            </div>
            <div class="col-md-2">
                {% if request.user.is_superuser %}
                    <div class="float-right">
                        <button type="button" id="add_announcement" class="btn btn-outline-primary waves-effect waves-light">Add</button>
                    </div>
                {% endif %}

            </div>
        </div>
    <div class="col-md-12">
        {% for announcement in announcements %}
            <div style="margin-bottom: 50px">
            <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-10">
                    {{ announcement.title }}
                    </div>
                <div class="col-md-2">
                    <div class="float-right">
                         <p class="card-text">
                    {{ announcement.create_time | date:"Y-m-d H:i:s" }}
                    </p>
                    </div>

                </div>
                </div>

            </div>
            <div class="card-body">
                {{ announcement.description|safe }}
                <div class="row">
                    <div class="col-md-7">

                    </div>
                    <div class="col-md-5">
                        <div class="float-right">
                            <h4>Creator: {{ announcement.create_author.username }}</h4>
                        </div>

                    </div>

                </div>
            </div>
        </div>
            </div>
        {% endfor %}
    </div>

    </div>
{% endblock %}

{% block myjs %}
    {{ block.super }}
    <script type="text/javascript">
     $("#add_announcement").click(function () {
         location.href ="{% url 'contest:create_announcement' contest_id %}";
     });
    </script>
{% endblock %}

contest/templates/contest_problem_detail.html
{% extends 'base_contest.html' %}

{% block title %}
{{ ptc.contest.title }} | {{ ptc.p_id }}
{% endblock %}

{% block mycss %}
    <link rel="stylesheet" href="/static/css/oj.css">
    <link rel="stylesheet" href="/static/assets/plugins/ckeditor/plugins/codesnippet/lib/highlight/styles/github.css">
    <script src="/static/assets/hl/js/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <style type="text/css">
    .problem_info{
            margin-top: 2px;
            margin-bottom: 12px;
        }
    </style>
{% endblock %}

{% block leftcard %}
    <div class="col-md-10">
        <div class="card">
            <div class="card-body">
                <div data-v-ecbd690c="" class="ivu-card ivu-card-dis-hover ivu-card-shadow">
                    <div class="ivu-card-head">
                        <div class="panel-title">
                            <div data-v-ecbd690c=""><span style="font-size: 25pt">{{ ptc.problem.title }}</span></div>
                        </div>
                    </div>
                    <div class="ivu-card-extra">
                        <div class="panel-extra"></div>
                    </div>
                    <div class="ivu-card-body" style="padding: 40px;">
                        <div class="panel-body">
                            <div data-v-ecbd690c="" id="problem-content" class="markdown-body">
                                <p data-v-ecbd690c="" class="title">Description</p>
                                <p data-v-ecbd690c="" class="content">
                                    {{ ptc.problem.content|safe }}
                                </p>
                                <p data-v-ecbd690c="" class="title">Input
                                    <!---->
                                </p>
                                <p data-v-ecbd690c="" class="content">
                                    {{ ptc.problem.input|safe }}
                                </p>
                                <p data-v-ecbd690c="" class="title">Output
                                    <!---->
                                </p>
                                <p data-v-ecbd690c="" class="content">
                                    {{ ptc.problem.output|safe }}
                                </p>
                                <div data-v-ecbd690c="">
                                    {% for simple in ptc.problem.simple_put_set.all %}
                                        <div data-v-ecbd690c="" class="flex-container sample">
                                            <div data-v-ecbd690c="" class="sample-input">
                                                <p data-v-ecbd690c="" class="title">Sample Input {{ forloop.counter }}
                                                </p>
                                                <pre data-v-ecbd690c="">{{ simple.simple_input|safe }}</pre>
                                            </div>
                                            <div data-v-ecbd690c="" class="sample-output">
                                                <p data-v-ecbd690c="" class="title">Sample Output {{ forloop.counter }}</p>
                                                <pre data-v-ecbd690c="">{{ simple.simple_output|safe }}</pre>

                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                                {% if ptc.problem.hint == "" %}

                                {% else %}
                                    <div data-v-ecbd690c="">
                                    <p data-v-ecbd690c="" class="title">Hint</p>
                                    <div data-v-ecbd690c=""
                                         class="ivu-card ivu-card-bordered ivu-card-dis-hover">
                                        <!---->
                                        <!---->
                                        <div class="ivu-card-body">
                                            <div data-v-ecbd690c="" class="content">
                                                {{ ptc.problem.hint|safe }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                </div>
        </div>

    </div>
{% endblock %}

{% block rightcard %}
    <div class="col-md-2 mb-5">
    <div class="col-md-12" style="padding: 0">
        <div class="card card-sm" style="height:296px;margin-bottom:2rem;">
            <div class="list-group mailbox-menu-actual d-lg-block" id="navigation">

            <a class="list-group-item list-group-item-action" id="overview" href="/contest/{{ contest_id }}/overview" style="height: 60px;padding-top: 20px;padding-bottom: 20px">
                    <i class="batch-icon batch-icon-home"></i>
                OverView
            </a>
            <a class="list-group-item list-group-item-action" id="announcement" href="/contest/{{ contest_id }}/announcements" style="height: 60px;padding-top: 20px;padding-bottom: 20px">
                    <i class="batch-icon batch-icon-list"></i>
                Announcements
            </a>
            <a class="list-group-item list-group-item-action" id="problem" href="/contest/{{ contest_id }}/problems" style="height: 60px;padding-top: 20px;padding-bottom: 20px">
                    <i class="batch-icon batch-icon-compose-alt-2"></i>
                Problems
            </a>
            <a class="list-group-item list-group-item-action" id="submission" href="/contest/{{ contest_id }}/submissions" style="height: 60px;padding-top: 20px;padding-bottom: 20px">
                    <i class="batch-icon batch-icon-newspaper"></i>
                Submissions
            </a>
            <a class="list-group-item list-group-item-action" id="rank" href="/contest/{{ contest_id }}/rank" style="height: 60px;padding-top: 20px;padding-bottom: 20px">
                    <i class="batch-icon batch-icon-flag"></i>
                Rankings
            </a>

        </div>
    </div>
    </div>
    <div class="col-md-12" style="padding: 0">
        <div class="card card-sm" style="height: 380px;">
                            <div class="card-header">
                                <i class="batch-icon batch-icon-spam"></i> 题目信息
                            </div>
                            <div class="card-body" style="padding-top: 15px">
                                <div class="row">
                                    <div class="col-md-6">ID</div>
                                    <div class="col-md-6"><p class="float-right">{{ ptc.p_id }}</p> </div>
                                </div>
                                <hr class="problem_info">
                                 <div class="row">
                                    <div class="col-md-6">时间限制</div>
                                    <div class="col-md-6"><p class="float-right">{{ ptc.problem.time_limit }}ms</p> </div>
                                </div>
                                <hr class="problem_info">
                                 <div class="row">
                                    <div class="col-md-6">内存限制</div>
                                    <div class="col-md-6"><p class="float-right">{{ ptc.problem.mem_limit }}KB</p> </div>
                                </div>
                                <hr class="problem_info">
                                <div class="row">
                                    <div class="col-md-6">难度</div>
                                    <div class="col-md-6"><p class="float-right">{{ ptc.problem.level }}</p> </div>
                                </div>
                                <hr class="problem_info">
                                <div class="row">
                                    <div class="col-md-6">判题规则</div>
                                    <div class="col-md-6"><p class="float-right">{{ ptc.problem.rule }}</p> </div>
                                </div>
                                <hr class="problem_info">
                                <div class="row">
                                    <div class="col-md-6">提交(AC/Total)</div>
                                    <div class="col-md-6"><p class="float-right"><a id="ac" href="javascript:void(0)">{{ ptc.ac_num }}</a>/<a id="total" href="javascript:void(0)">{{ ptc.total_num }}</a></p> </div>
                                </div>
                                <hr class="problem_info">
                            </div>
                        </div>
    </div>
    </div>
    <div class="col-md-10 mb-5" style="margin-top: 2rem">
    <div class="card">
            <div class="card-body">
                <div class="row pb-5">
                    <div class="col-lg-12 row" style="margin-top:20px">

                        <div class="col-lg-1"></div>
                        <label for="input-task-details"
                               style="font-size:2rem">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Language:</label>
                        <div class="col-lg-2">

                            <select class="form-control input-task-priority"
                                    id="language">
                                <option value="python3">Python3</option>
                                <option value="java">Java</option>
                                <option value="g++" selected="selected">C++</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-1"></div>
                    <div class="col-lg-9">
                        <pre id="code" class="ace_editor" style="min-height:400px"><textarea
                                class="ace_text-input"></textarea></pre>
                    </div>
                    <div class="col-lg-9"></div>
                    <button type="button" id="code_btn" class="btn btn-warning waves-effect waves-light">submit
                    </button>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block myjs %}
    {{ block.super }}
    <script src="http://cdn.bootcss.com/ace/1.2.4/ace.js"></script>
    <script src="http://cdn.bootcss.com/ace/1.2.4/ext-language_tools.js"></script>
    {% csrf_token %}
    <script>
        editor = ace.edit("code");

        //设置风格和语言（更多风格和语言，请到github上相应目录查看）
        theme = "dawn";
        language = "c_cpp";
        editor.setTheme("ace/theme/" + theme);
        editor.session.setMode("ace/mode/" + language);

        //字体大小
        editor.setFontSize(18);

        //设置只读（true时只读，用于展示代码）
        editor.setReadOnly(false);

        //自动换行,设置为off关闭
        editor.setOption("wrap", "free");

        //启用提示菜单
        ace.require("ace/ext/language_tools");

       $("#language").change(function () {
         language=$("#language").val();
         if(language==="python3")
             language="python";
         editor.session.setMode("ace/mode/" + language);
       });

        $("#code_btn").click(function () {
            $.ajax({
                url: "",
                type: "post",
                data: {
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                    code: editor.getValue(),
                    language: $("#language").val(),
                },
                success: function (data) {
                    console.log(data);
                    if (data.status) {
                        location.href = "/contest/{{ contest_id|urlencode }}/submissions"
                    } else {
                        $(".errors").text(data.msg);
                        alert(data.msg)
                    }
                }
            })
        });

        $("#ac").click(function () {
            search="{{ problem.title }}";
            search = encodeURIComponent(search);
            location.href="/contest/{{ contest_id|urlencode }}/submissions?status=1&search="+search
        });

        $("#total").click(function () {
            search="{{ problem.title }}";
            search = encodeURIComponent(search);
            location.href="/contest/{{ contest_id|urlencode }}/submissions?status=-1&search="+search
        })

    </script>
{% endblock %}

contest/templates/contest_rank.html
{% extends 'base_contest.html' %}

{% block title %}
{{ contest.title }} | Rank
{% endblock %}

{% block mycss %}

{% endblock %}

{% block leftcard %}
    <div class="col-md-10">
        <div class="card">
            <div class="card-header">
                <div class="row">
                <div class="col-md-12">
                    <h1>{{ contest.title }}</h1>
                </div>
            </div>
            </div>
            <div class="card-table table-responsive">
                <table class="table table-hover align-middle">
                    <thead class="thead-light">
                        <tr>
                            <th>#</th>
                            <th>User</th>
                            <th>AC/Total</th>
                            <th>TotalTime</th>
                            {% for  ptc in contest.problem_to_contest_set.all %}
                                <th style="width: {{ width }}px">{{ ptc.p_id }}({{ ptc.ac_num }}/{{ ptc.total_num }})</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                    {% for ctu in ctus %}
                        <tr>
                            <td>
                                <div class="media">
                                    <div class="media-body">
                                        <div class="heading mt-1">
                                            {{ forloop.counter }}
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <a href="#">{{ ctu.user.username }}</a>
                            </td>
                            <td>
                                <a>{{ ctu.ac_number }}</a>/<a>{{ ctu.total_number }}</a>
                            </td>
                            <td>{{ ctu.total_time }}</td>
                            {% for cup in ctu.contest_user_problem_set.all %}

                                 {% if cup.ac_number > 0 %}
                                     <td style="background-color: #e2efda;max-width: 200px;">{{ cup.ac_time }}
                                     {% if cup.wrong_number > 0 %}
                                        (-{{ cup.wrong_number }})
                                     {% endif %}</td>
                                 {% elif cup.wrong_number > 0 %}
                                     <td style="background-color: #efdede;max-width: 200px;">(-{{ cup.wrong_number }})</td>
                                 {% endif %}


                            {% endfor %}


                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% include 'page.html' %}
        </div>
    </div>
{% endblock %}

{% block myjs %}
    {{ block.super }}
    <script type="text/javascript">



        function new_page(p_num) {
            location.href= '/contest/{{ contest_id }}/rank?' + "&page=" + p_num
        }
    </script>
{% endblock %}